// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ODPC.Data;

#nullable disable

namespace ODPC.Migrations
{
    [DbContext(typeof(OdpcDbContext))]
    [Migration("20250528112843_AddGebruikersgroepPublicatie")]
    partial class AddGebruikersgroepPublicatie
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ODPC.Data.Entities.Gebruikersgroep", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("text");

                    b.HasKey("Uuid");

                    b.ToTable("Gebruikersgroepen");
                });

            modelBuilder.Entity("ODPC.Data.Entities.GebruikersgroepGebruiker", b =>
                {
                    b.Property<string>("GebruikerId")
                        .HasColumnType("text");

                    b.Property<Guid>("GebruikersgroepUuid")
                        .HasColumnType("uuid");

                    b.HasKey("GebruikerId", "GebruikersgroepUuid");

                    b.HasIndex("GebruikersgroepUuid");

                    b.ToTable("GebruikersgroepGebruikers");
                });

            modelBuilder.Entity("ODPC.Data.Entities.GebruikersgroepPublicatie", b =>
                {
                    b.Property<Guid>("GebruikersgroepUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PublicatieUuid")
                        .HasColumnType("uuid");

                    b.HasKey("GebruikersgroepUuid", "PublicatieUuid");

                    b.ToTable("GebruikersgroepPublicatie");
                });

            modelBuilder.Entity("ODPC.Data.Entities.GebruikersgroepWaardelijst", b =>
                {
                    b.Property<Guid>("GebruikersgroepUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("WaardelijstId")
                        .HasColumnType("text");

                    b.HasKey("GebruikersgroepUuid", "WaardelijstId");

                    b.ToTable("GebruikersgroepWaardelijsten");
                });

            modelBuilder.Entity("ODPC.Data.Entities.GebruikersgroepGebruiker", b =>
                {
                    b.HasOne("ODPC.Data.Entities.Gebruikersgroep", "Gebruikersgroep")
                        .WithMany("GebruikersgroepGebruikers")
                        .HasForeignKey("GebruikersgroepUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruikersgroep");
                });

            modelBuilder.Entity("ODPC.Data.Entities.GebruikersgroepPublicatie", b =>
                {
                    b.HasOne("ODPC.Data.Entities.Gebruikersgroep", "Gebruikersgroep")
                        .WithMany()
                        .HasForeignKey("GebruikersgroepUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruikersgroep");
                });

            modelBuilder.Entity("ODPC.Data.Entities.GebruikersgroepWaardelijst", b =>
                {
                    b.HasOne("ODPC.Data.Entities.Gebruikersgroep", "Gebruikersgroep")
                        .WithMany("Waardelijsten")
                        .HasForeignKey("GebruikersgroepUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruikersgroep");
                });

            modelBuilder.Entity("ODPC.Data.Entities.Gebruikersgroep", b =>
                {
                    b.Navigation("GebruikersgroepGebruikers");

                    b.Navigation("Waardelijsten");
                });
#pragma warning restore 612, 618
        }
    }
}
