# Generated by Django 4.2.20 on 2025-05-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="The system identifier that uniquely identifies the user performing the action.",
                        max_length=255,
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="The display name of the user.",
                        max_length=255,
                        verbose_name="naam",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisation member",
                "verbose_name_plural": "organisation members",
            },
        ),
    ]
