# Generated by Django 5.2.3 on 2025-06-25 08:56

from collections.abc import Sequence

from django.db import migrations
from django.db.migrations.state import StateApps


class RenameGroups:
    def __init__(self, name_pairs: Sequence[tuple[str, str]]):
        self.name_pairs = name_pairs

    def __call__(self, apps: StateApps, _) -> None:
        Group = apps.get_model("auth", "Group")

        groups = Group.objects.all()
        if not groups:
            return

        groups_by_name = {group.name: group for group in groups}

        for old_name, new_name in self.name_pairs:
            if old_name not in groups_by_name:
                continue
            if new_name in groups_by_name:
                continue

            group = groups_by_name[old_name]
            group.name = new_name
            group.save()


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0001_initial"),
        ("accounts", "0003_organisationmember"),
    ]

    operations = [
        migrations.RunPython(
            RenameGroups(
                [
                    ("Technisch beheer", "TechnischBeheer"),
                    ("Functioneel beheer", "FunctioneelBeheer"),
                ]
            ),
            reverse_code=RenameGroups(
                [
                    ("TechnischBeheer", "Technisch beheer"),
                    ("FunctioneelBeheer", "Functioneel beheer"),
                ]
            ),
        )
    ]
