# Generated by Django 5.2.10 on 2026-01-07 10:34
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationUnit",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text=(
                            "The system identifier that uniquely identifies the "
                            "organisation unit performing the action."
                        ),
                        max_length=255,
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="The display name of the organisation unit.",
                        max_length=255,
                        verbose_name="naam",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisation unit",
                "verbose_name_plural": "organisation units",
            },
        ),
    ]
