# Generated by Django 5.2.10 on 2026-01-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_organisationunit"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="organisationmember",
            index=models.Index(
                fields=["identifier"], name="accounts_or_identif_56655c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organisationunit",
            index=models.Index(
                fields=["identifier"], name="accounts_or_identif_358179_idx"
            ),
        ),
    ]
