# Generated by Django 5.2.10 on 2026-01-12 10:05

from django.db import migrations, models

import woo_publications.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_organisationmember_accounts_or_identif_56655c_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisationunit",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="organisationunit",
            name="identifier",
            field=models.SlugField(
                default=woo_publications.accounts.models.uuid_slug,
                help_text="The system identifier that uniquely identifies the organisation unit performing the action.",
                max_length=255,
                unique=True,
                verbose_name="identifier",
            ),
        ),
    ]
