# Generated by Django 4.2.19 on 2025-03-28 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0007_alter_organisation_is_actief"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationcategory",
            name="archiefnominatie",
            field=models.CharField(
                choices=[("blijvend_bewaren", "Retain"), ("vernietigen", "Destroy")],
                default="blijvend_bewaren",
                help_text="Determines if the archived data will be retained or destroyed.",
                max_length=50,
                verbose_name="archive action",
            ),
        ),
        migrations.AddField(
            model_name="informationcategory",
            name="bewaartermijn",
            field=models.PositiveIntegerField(
                default=10,
                help_text="The retention period in years.",
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="retention period",
            ),
        ),
        migrations.AddField(
            model_name="informationcategory",
            name="bron_bewaartermijn",
            field=models.CharField(
                default="",
                help_text="The source of the retention policy (example: Selectielijst gemeenten 2020).",
                max_length=255,
                verbose_name="retention policy source",
            ),
        ),
        migrations.AddField(
            model_name="informationcategory",
            name="selectiecategorie",
            field=models.CharField(
                blank=True,
                help_text="The category as specified in the provided retention policy source (example: 20.1.2).",
                max_length=255,
                verbose_name="selection category",
            ),
        ),
        migrations.AddField(
            model_name="informationcategory",
            name="toelichting_bewaartermijn",
            field=models.TextField(
                blank=True, verbose_name="retention policy explanation"
            ),
        ),
    ]
