# Generated by Django 4.2.19 on 2025-04-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0008_informationcategory_archiefnominatie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationcategory",
            name="archiefnominatie",
            field=models.CharField(
                choices=[("blijvend_bewaren", "Retain"), ("vernietigen", "Dispose")],
                default="blijvend_bewaren",
                help_text="Determines if the archived data will be retained or disposed.",
                max_length=50,
                verbose_name="archive action",
            ),
        ),
    ]
