# Generated by Django 5.2.1 on 2025-06-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0009_alter_informationcategory_archiefnominatie"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationcategory",
            name="omschrijving",
            field=models.TextField(
                blank=True,
                help_text="The brief explanation shown to employees and citizens.",
                verbose_name="description",
            ),
        ),
    ]
