# Generated by Django 5.2.3 on 2025-07-03 16:20

import woo_publications.config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0010_informationcategory_omschrijving"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="rsin",
            field=models.CharField(
                blank=True,
                help_text="The RSIN of the organisation.",
                max_length=9,
                validators=[woo_publications.config.validators.validate_rsin],
                verbose_name="RSIN",
            ),
        ),
    ]
