# Generated by Django 4.2.19 on 2025-02-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0012_alter_document_bestandsomvang"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="upload_complete",
            field=models.BooleanField(
                default=False,
                help_text="Marker to indicate if the upload to the Documenten API is finalized.",
                verbose_name="upload completed",
            ),
        ),
    ]
