# Generated by Django 4.2.19 on 2025-02-12 16:15

from django.db import migrations


def mark_completed(apps, _):
    Document = apps.get_model("publications", "Document")
    Document.objects.exclude(lock="").update(upload_complete=True, lock="")


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0013_document_upload_complete"),
    ]

    operations = [
        migrations.RunPython(mark_completed, migrations.RunPython.noop),
    ]
