# Generated by Django 4.2.19 on 2025-04-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0016_publication_onderwerpen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="publicatiestatus",
            field=models.CharField(
                choices=[
                    ("gepubliceerd", "Published"),
                    ("concept", "Concept"),
                    ("ingetrokken", "Revoked"),
                ],
                default="gepubliceerd",
                max_length=12,
                verbose_name="status",
            ),
        ),
    ]
