# Generated by Django 4.2.19 on 2025-04-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0018_publication_archiefactiedatum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="archiefactiedatum",
            field=models.DateField(
                blank=True,
                help_text="Date when the publication will be archived or disposed.",
                null=True,
                verbose_name="archive action date",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="archiefnominatie",
            field=models.CharField(
                blank=True,
                choices=[("blijvend_bewaren", "Retain"), ("vernietigen", "Dispose")],
                help_text="Determines if the archived data will be retained or disposed.",
                max_length=50,
                verbose_name="archive action",
            ),
        ),
    ]
