# Generated by Django 4.2.19 on 2025-04-16 16:33

import django.core.validators
from django.db import migrations, models

import woo_publications.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0019_alter_publication_archiefactiedatum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="afbeelding",
            field=models.ImageField(
                default="",
                upload_to="topics/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                    ),
                    woo_publications.utils.validators.max_img_size_validator,
                    woo_publications.utils.validators.max_img_width_and_height_validator,
                ],
                verbose_name="Afbeelding",
            ),
            preserve_default=False,
        ),
    ]
