# Generated by Django 5.2.1 on 2025-05-23 13:39

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0021_document_eigenaar_publication_eigenaar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="publicatiestatus",
            field=django_fsm.FSMField(
                choices=[
                    ("gepubliceerd", "Published"),
                    ("concept", "Concept"),
                    ("ingetrokken", "Revoked"),
                ],
                max_length=12,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="publicatiestatus",
            field=django_fsm.FSMField(
                choices=[
                    ("gepubliceerd", "Published"),
                    ("concept", "Concept"),
                    ("ingetrokken", "Revoked"),
                ],
                max_length=12,
                verbose_name="status",
            ),
        ),
    ]
