# Generated by Django 5.2.1 on 2025-06-10 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0022_alter_document_publicatiestatus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kenmerk",
                    models.CharField(
                        help_text="The identifier that (combined with bron) uniquely identifies the publication.",
                        max_length=40,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "bron",
                    models.CharField(
                        help_text="Determines where the identifier is defined and sourced from.",
                        max_length=40,
                        verbose_name="source",
                    ),
                ),
                (
                    "publicatie",
                    models.ForeignKey(
                        help_text="The publication that this identifier identifies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publications.publication",
                        verbose_name="publication",
                    ),
                ),
            ],
            options={
                "verbose_name": "kenmerk",
                "verbose_name_plural": "kenmerken",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kenmerk", "bron"), name="unique_identifier"
                    )
                ],
            },
        ),
    ]
