# Generated by Django 5.2.1 on 2025-06-10 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0023_publicationidentifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kenmerk",
                    models.CharField(
                        help_text="The identifier that (combined with bron) uniquely identifies the document.",
                        max_length=40,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "bron",
                    models.CharField(
                        help_text="Determines where the identifier is defined and sourced from.",
                        max_length=40,
                        verbose_name="source",
                    ),
                ),
            ],
            options={
                "verbose_name": "kenmerk",
                "verbose_name_plural": "kenmerken",
            },
        ),
        migrations.RemoveConstraint(
            model_name="publicationidentifier",
            name="unique_identifier",
        ),
        migrations.AddConstraint(
            model_name="publicationidentifier",
            constraint=models.UniqueConstraint(
                fields=("kenmerk", "bron"), name="unique_publication_identifier"
            ),
        ),
        migrations.AddField(
            model_name="documentidentifier",
            name="document",
            field=models.ForeignKey(
                help_text="The document that this identifier identifies.",
                on_delete=django.db.models.deletion.CASCADE,
                to="publications.document",
                verbose_name="document",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentidentifier",
            constraint=models.UniqueConstraint(
                fields=("kenmerk", "bron"), name="unique_document_identifier"
            ),
        ),
    ]
