# Generated by Django 5.2.1 on 2025-06-17 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_organisationmember"),
        ("metadata", "0010_informationcategory_omschrijving"),
        ("publications", "0024_documentidentifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="publisher",
            field=models.ForeignKey(
                help_text="The organisation which publishes the publication.",
                limit_choices_to={"is_actief": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_publications",
                to="metadata.organisation",
                verbose_name="publisher",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(  # pyright: ignore[reportCallIssue]
                condition=models.Q(  # pyright: ignore[reportCallIssue]
                    ("publisher__isnull", False),
                    ("publicatiestatus", "concept"),
                    ("publicatiestatus", ""),
                    _connector="OR",
                ),
                name="publisher_null_only_for_concept_or_blank",
                violation_error_message="The publisher is only allowed to be unset if the publication is a concept.",
            ),
        ),
    ]
