# Generated by Django 5.2.3 on 2025-06-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0025_alter_publication_publisher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="datum_ondertekend",
            field=models.DateTimeField(
                blank=True,
                help_text="The timestamp when the document is signed by the organisatie.",
                null=True,
                verbose_name="signed date",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="gepubliceerd_op",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="System timestamp reflecting when the publication was published.",
                null=True,
                verbose_name="published on",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="ingetrokken_op",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="System timestamp reflecting when the publication was revoked.",
                null=True,
                verbose_name="revoked on",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="ontvangstdatum",
            field=models.DateTimeField(
                blank=True,
                help_text="The timestamp when the document is received by the organisatie.",
                null=True,
                verbose_name="date of reception",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="datum_begin_geldigheid",
            field=models.DateField(
                blank=True,
                help_text="The date when the rights and obligations of the attached documents come into effect.",
                null=True,
                verbose_name="start date",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="datum_einde_geldigheid",
            field=models.DateField(
                blank=True,
                help_text="The date when the rights and obligations of the attached documents stops being in effect.",
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="gepubliceerd_op",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="System timestamp reflecting when the publication was published.",
                null=True,
                verbose_name="published on",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="ingetrokken_op",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="System timestamp reflecting when the publication was revoked.",
                null=True,
                verbose_name="revoked on",
            ),
        ),
    ]
