# Generated by Django 5.2.3 on 2025-06-25 22:33

from django.db import migrations, models
from django.db.migrations.state import StateApps

from woo_publications.publications.constants import PublicationStatusOptions


# old items might not have gepubliceerd_op set.
# so make sure that they are backfilled correctly
# to prevent errors for [#283]
def sync_published_on(apps: StateApps, _):
    Document = apps.get_model("publications", "document")
    Publication = apps.get_model("publications", "publication")

    for doc in Document.objects.filter(
        ~models.Q(publicatiestatus=PublicationStatusOptions.concept),
        gepubliceerd_op=None
    ):
        doc.gepubliceerd_op = doc.registratiedatum
        doc.save()

    for pub in Publication.objects.filter(
        ~models.Q(publicatiestatus=PublicationStatusOptions.concept),
        gepubliceerd_op=None
    ):
        pub.gepubliceerd_op = pub.registratiedatum
        pub.save()

class Migration(migrations.Migration):

    dependencies = [
        (
            "publications",
            "0026_document_datum_ondertekend_document_gepubliceerd_op_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(sync_published_on, migrations.RunPython.noop),
    ]
