# Generated by Django 5.2.3 on 2025-06-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "publications",
            "0026_document_datum_ondertekend_document_gepubliceerd_op_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="documentidentifier",
            name="unique_document_identifier",
        ),
        migrations.RemoveConstraint(
            model_name="publicationidentifier",
            name="unique_publication_identifier",
        ),
        migrations.AddConstraint(
            model_name="documentidentifier",
            constraint=models.UniqueConstraint(
                fields=("document", "kenmerk", "bron"),
                name="no_duplicate_document_identifiers",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationidentifier",
            constraint=models.UniqueConstraint(
                fields=("publicatie", "kenmerk", "bron"),
                name="no_duplicate_publication_identifiers",
            ),
        ),
    ]
