# Generated by Django 5.2.3 on 2025-06-26 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0027_auto_20250626_0033"),
        (
            "publications",
            "0027_remove_documentidentifier_unique_document_identifier_and_more",
        ),
    ]

    operations = []
