# Generated by Django 5.2.3 on 2025-07-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0028_merge_20250626_0914"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="soort_handeling",
        ),
    ]
