# Generated by Django 5.2.3 on 2025-07-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0029_remove_document_soort_handeling"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="If the document originates from a Documenten API, this URL uniquely identifies the matching resource. The value is empty for manual uploads.",
                max_length=1000,
                verbose_name="source URL",
            ),
        ),
    ]
