# Generated by Django 5.2.3 on 2025-07-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0030_document_source_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentidentifier",
            options={
                "verbose_name": "identifier",
                "verbose_name_plural": "identifiers",
            },
        ),
        migrations.AlterModelOptions(
            name="publicationidentifier",
            options={
                "verbose_name": "identifier",
                "verbose_name_plural": "identifiers",
            },
        ),
    ]
