# Generated by Django 5.2.4 on 2025-07-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0031_alter_documentidentifier_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="datum_begin_geldigheid",
            field=models.DateField(
                blank=True,
                help_text="The date when the rights and obligations of the attached documents come into effect.",
                null=True,
                verbose_name="in effect from",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="datum_einde_geldigheid",
            field=models.DateField(
                blank=True,
                help_text="The date when the rights and obligations of the attached documents stops being in effect.",
                null=True,
                verbose_name="in effect until",
            ),
        ),
    ]
