# Generated by Django 5.2.10 on 2026-01-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_organisationunit"),
        ("publications", "0032_alter_publication_datum_begin_geldigheid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="eigenaar_groep",
            field=models.ForeignKey(
                blank=True,
                help_text="The organisation unit owning this publication, from gpp-app or gpp-publicatiebank. Any member in the referenced group can manage this publication.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.organisationunit",
                verbose_name="owner (group)",
            ),
        ),
    ]
