# Generated by Django 4.2.19 on 2025-02-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0022_set_default_service_slug"),
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="documents_api_service",
            field=models.ForeignKey(
                help_text="The service to use for new document uploads - the metadata and binary content will be sent to this API.",
                limit_choices_to={"api_type": "drc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Documents API service",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="gpp_search_service",
            field=models.ForeignKey(
                help_text="The service to use for search index operations to make the content publicly available.",
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="GPP Search service",
            ),
        ),
    ]
