# Generated by Django 5.2.1 on 2025-06-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0002_globalconfiguration_gpp_search_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="gpp_app_publication_url_template",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL pattern to a publication in the GPP app. The special token <UUID> will be replaced with the system identifier of each publication.",
                max_length=500,
                verbose_name="GPP-app publication URL template",
            ),
        ),
    ]
